### ISSUE TITLE
Add Support For CarthageDEX

### ISSUE THREAD

**Issue by samisbakedham** [defisaver/defisaver-v3-contracts#150]
Hi,
CarthageDEX is a fork of uniswap built on Candle chain. Would love to see it supported on defisaver. Website: https://app.carthagedex.com/#/candle

**Comment by majkic99** [comment]
We are not available on Candle chain at the moment

**Comment by samisbakedham** [comment]
> We are not available on Candle chain at the moment

Ok so can you reopen it instead of marking it as complete thank you
